### ISSUE TITLE
🐛 Bug: Text selection around the game should be disabled

### ISSUE THREAD

**Issue by ayo-run** [JoshuaKGoldberg/ChooseYourFramework#26]
Pressing/tapping and dragging triggers text selection 

![image](https://user-images.githubusercontent.com/4262489/186955751-810deb65-25ab-4f41-a781-b11abbd30a24.png)

**Comment by JoshuaKGoldberg** [comment]
Thanks for the spot @ayoayco! Agreed, you shouldn't be able to do that.

Modifying `src/index.css` should be the right place to add new styles. But, pending some infrastructural work in EightBittr, you'll have to manually copy over `src/index.css` to `lib/index.css` whenever you want it to be updated locally.

**Comment by ayo-run** [comment]
Sounds good! I'll try to set up the project and create a PR when I get time soon.

**Comment by ayo-run** [comment]
Hi @JoshuaKGoldberg, I set up the project according to the README (i.e., `yarn`, `yarn run hydrate`,` yarn run compile`), and encountered some errors. I'm running http-server on the `dist` folder. Maybe you have encountered this before? Don't know if this is the right place to ask 😅

<img width="1489" alt="Screen Shot 2022-08-28 at 6 00 20 PM" src="https://user-images.githubusercontent.com/4262489/187083420-9a0b8a3d-330f-4a6f-b7a0-0860ea5a61ca.png">

**Comment by JoshuaKGoldberg** [comment]
@ayoayco this is as good a place to ask as any - and sorry this isn't documented! You want to open `lib/index.html` directly. No need to run an http-server or anything.

https://github.com/FullScreenShenanigans/EightBittr/issues/336 tracks the lack of docs around getting started. This is very good user research to see what's not described - thank you for posting! 😅

**Comment by ayo-run** [comment]
Looks like the text selection happens on the buttons area that shows up on mobile. I was committing a fix on my machine then noticed some temporary files generated by vim is not ignored. I have a small PR to ignore vim temporary files: #30

Hope this is okay, for the vim users!
